spring:
  cloud:
    stream:
      bindings:
        messageConsumer-in-0:
          group: message-group
          destination: Message-Topic
          consumer:
            max-attempts: 1
            partitioned: true
      kafka:
        binder:
          brokers: localhost
          auto-add-partitions: true
          auto-alter-partitions: true
          auto-create-topics: false
          consumer-properties:
            allow.auto.create.topics: false
        default:
          producer:
            topic:
              replication-factor: 1
